version: 0.0
os: linux
files:
  - source: /
    destination: /etc/nginx
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root

